import datetime

from dateutil.tz import tzutc
from twitter import Media, User, Status


tweet_with_image_description = {'_json': {'contributors': None,
                                          'coordinates': None,
                                          'created_at': 'Thu Nov 09 18:23:44 +0000 2017',
                                          'display_text_range': [0, 4],
                                          'entities': {'hashtags': [],
                                                       'media': [{'display_url': 'pic.twitter.com/7t99pQqOgO',
                                                                  'expanded_url': 'https://twitter.com/moabridge/status/928689578566762497/photo/1',
                                                                  'id': 928689520525983744,
                                                                  'id_str': '928689520525983744',
                                                                  'indices': [5, 28],
                                                                  'media_url': 'http://pbs.twimg.com/media/DONeMtGUQAAadBf.png',
                                                                  'media_url_https': 'https://pbs.twimg.com/media/DONeMtGUQAAadBf.png',
                                                                  'sizes': {'large': {'h': 500,
                                                                                      'resize': 'fit',
                                                                                      'w': 500},
                                                                            'medium': {'h': 500,
                                                                                       'resize': 'fit',
                                                                                       'w': 500},
                                                                            'small': {'h': 500,
                                                                                      'resize': 'fit',
                                                                                      'w': 500},
                                                                            'thumb': {'h': 150,
                                                                                      'resize': 'crop',
                                                                                      'w': 150}},
                                                                  'type': 'photo',
                                                                  'url': 'https://t.co/7t99pQqOgO'}],
                                                       'symbols': [],
                                                       'urls': [],
                                                       'user_mentions': []},
                                          'extended_entities': {'media': [{'display_url': 'pic.twitter.com/7t99pQqOgO',
                                                                           'expanded_url': 'https://twitter.com/moabridge/status/928689578566762497/photo/1',
                                                                           'id': 928689520525983744,
                                                                           'id_str': '928689520525983744',
                                                                           'indices': [5, 28],
                                                                           'media_url': 'http://pbs.twimg.com/media/DONeMtGUQAAadBf.png',
                                                                           'media_url_https': 'https://pbs.twimg.com/media/DONeMtGUQAAadBf.png',
                                                                           'sizes': {'large': {'h': 500,
                                                                                               'resize': 'fit',
                                                                                               'w': 500},
                                                                                     'medium': {'h': 500,
                                                                                                'resize': 'fit',
                                                                                                'w': 500},
                                                                                     'small': {'h': 500,
                                                                                               'resize': 'fit',
                                                                                               'w': 500},
                                                                                     'thumb': {'h': 150,
                                                                                               'resize': 'crop',
                                                                                               'w': 150}},
                                                                           'type': 'photo',
                                                                           'url': 'https://t.co/7t99pQqOgO'}]},
                                          'favorite_count': 0,
                                          'favorited': False,
                                          'full_text': 'test https://t.co/7t99pQqOgO',
                                          'geo': None,
                                          'id': 928689578566762497,
                                          'id_str': '928689578566762497',
                                          'in_reply_to_screen_name': None,
                                          'in_reply_to_status_id': None,
                                          'in_reply_to_status_id_str': None,
                                          'in_reply_to_user_id': None,
                                          'in_reply_to_user_id_str': None,
                                          'is_quote_status': False,
                                          'lang': 'en',
                                          'place': None,
                                          'possibly_sensitive': False,
                                          'retweet_count': 0,
                                          'retweeted': False,
                                          'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web '
                                                    'Client</a>',
                                          'truncated': False,
                                          'user': {'contributors_enabled': False,
                                                   'created_at': 'Mon Oct 30 16:08:43 +0000 2017',
                                                   'default_profile': True,
                                                   'default_profile_image': True,
                                                   'description': '',
                                                   'entities': {'description': {'urls': []}},
                                                   'favourites_count': 0,
                                                   'follow_request_sent': False,
                                                   'followers_count': 0,
                                                   'following': False,
                                                   'friends_count': 0,
                                                   'geo_enabled': False,
                                                   'has_extended_profile': False,
                                                   'id': 925031723233972224,
                                                   'id_str': '925031723233972224',
                                                   'is_translation_enabled': False,
                                                   'is_translator': False,
                                                   'lang': 'en',
                                                   'listed_count': 0,
                                                   'location': '',
                                                   'name': 'Moa Bridge Test',
                                                   'notifications': False,
                                                   'profile_background_color': 'F5F8FA',
                                                   'profile_background_image_url': None,
                                                   'profile_background_image_url_https': None,
                                                   'profile_background_tile': False,
                                                   'profile_image_url': 'http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
                                                   'profile_image_url_https': 'https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
                                                   'profile_link_color': '1DA1F2',
                                                   'profile_sidebar_border_color': 'C0DEED',
                                                   'profile_sidebar_fill_color': 'DDEEF6',
                                                   'profile_text_color': '333333',
                                                   'profile_use_background_image': True,
                                                   'protected': True,
                                                   'screen_name': 'moabridge',
                                                   'statuses_count': 29,
                                                   'time_zone': None,
                                                   'translator_type': 'none',
                                                   'url': None,
                                                   'utc_offset': None,
                                                   'verified': False}},
                                'contributors': None,
                                'coordinates': None,
                                'created_at': 'Thu Nov 09 18:23:44 +0000 2017',
                                'current_user_retweet': None,
                                'favorite_count': 0,
                                'favorited': False,
                                'full_text': 'test https://t.co/7t99pQqOgO',
                                'geo': None,
                                'hashtags': [],
                                'id': 928689578566762497,
                                'id_str': '928689578566762497',
                                'in_reply_to_screen_name': None,
                                'in_reply_to_status_id': None,
                                'in_reply_to_user_id': None,
                                'lang': 'en',
                                'location': None,
                                'media': [
                                    Media(ID=928689520525983744, Type='photo',
                                          DisplayURL='pic.twitter.com/7t99pQqOgO')],
                                'param_defaults': {'contributors': None,
                                                   'coordinates': None,
                                                   'created_at': None,
                                                   'current_user_retweet': None,
                                                   'favorite_count': None,
                                                   'favorited': None,
                                                   'full_text': None,
                                                   'geo': None,
                                                   'hashtags': None,
                                                   'id': None,
                                                   'id_str': None,
                                                   'in_reply_to_screen_name': None,
                                                   'in_reply_to_status_id': None,
                                                   'in_reply_to_user_id': None,
                                                   'lang': None,
                                                   'location': None,
                                                   'media': None,
                                                   'place': None,
                                                   'possibly_sensitive': None,
                                                   'quoted_status': None,
                                                   'quoted_status_id': None,
                                                   'quoted_status_id_str': None,
                                                   'retweet_count': None,
                                                   'retweeted': None,
                                                   'retweeted_status': None,
                                                   'scopes': None,
                                                   'source': None,
                                                   'text': None,
                                                   'truncated': None,
                                                   'urls': None,
                                                   'user': None,
                                                   'user_mentions': None,
                                                   'withheld_copyright': None,
                                                   'withheld_in_countries': None,
                                                   'withheld_scope': None},
                                'place': None,
                                'possibly_sensitive': False,
                                'quoted_status': None,
                                'quoted_status_id': None,
                                'quoted_status_id_str': None,
                                'retweet_count': 0,
                                'retweeted': False,
                                'retweeted_status': None,
                                'scopes': None,
                                'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
                                'text': None,
                                'truncated': False,
                                'tweet_mode': 'extended',
                                'urls': [],
                                'user': User(ID=925031723233972224, ScreenName='moabridge'),
                                'user_mentions': [],
                                'withheld_copyright': None,
                                'withheld_in_countries': None,
                                'withheld_scope': None}


retweet_without_comment = {'_json': {'contributors': None,
                                     'coordinates': None,
                                     'created_at': 'Thu Nov 09 21:58:51 +0000 2017',
                                     'display_text_range': [0, 140],
                                     'entities': {'hashtags': [],
                                                  'symbols': [],
                                                  'urls': [],
                                                  'user_mentions': [{'id': 19394188,
                                                                     'id_str': '19394188',
                                                                     'indices': [3, 17],
                                                                     'name': 'John McCain',
                                                                     'screen_name': 'SenJohnMcCain'}]},
                                     'favorite_count': 0,
                                     'favorited': False,
                                     'full_text': 'RT @SenJohnMcCain: The allegations against Roy Moore '
                                                  'are deeply disturbing and disqualifying. He should '
                                                  'immediately step aside and allow th…',
                                     'geo': None,
                                     'id': 928743713047588864,
                                     'id_str': '928743713047588864',
                                     'in_reply_to_screen_name': None,
                                     'in_reply_to_status_id': None,
                                     'in_reply_to_status_id_str': None,
                                     'in_reply_to_user_id': None,
                                     'in_reply_to_user_id_str': None,
                                     'is_quote_status': False,
                                     'lang': 'en',
                                     'place': None,
                                     'retweet_count': 12986,
                                     'retweeted': True,
                                     'retweeted_status': {'contributors': None,
                                                          'coordinates': None,
                                                          'created_at': 'Thu Nov 09 19:44:32 +0000 2017',
                                                          'display_text_range': [0, 182],
                                                          'entities': {'hashtags': [],
                                                                       'symbols': [],
                                                                       'urls': [],
                                                                       'user_mentions': []},
                                                          'favorite_count': 37848,
                                                          'favorited': False,
                                                          'full_text': 'The allegations against Roy '
                                                                       'Moore are deeply disturbing and '
                                                                       'disqualifying. He should '
                                                                       'immediately step aside and allow '
                                                                       'the people of Alabama to elect a '
                                                                       'candidate they can be proud of.',
                                                          'geo': None,
                                                          'id': 928709913953624066,
                                                          'id_str': '928709913953624066',
                                                          'in_reply_to_screen_name': None,
                                                          'in_reply_to_status_id': None,
                                                          'in_reply_to_status_id_str': None,
                                                          'in_reply_to_user_id': None,
                                                          'in_reply_to_user_id_str': None,
                                                          'is_quote_status': False,
                                                          'lang': 'en',
                                                          'place': None,
                                                          'retweet_count': 12986,
                                                          'retweeted': True,
                                                          'source': '<a '
                                                                    'href="https://about.twitter.com/products/tweetdeck" '
                                                                    'rel="nofollow">TweetDeck</a>',
                                                          'truncated': False,
                                                          'user': {'contributors_enabled': False,
                                                                   'created_at': 'Fri Jan 23 13:42:31 '
                                                                                 '+0000 2009',
                                                                   'default_profile': False,
                                                                   'default_profile_image': False,
                                                                   'description': 'U.S. Senator John '
                                                                                  'McCain (R-AZ), '
                                                                                  'Chairman of Senate '
                                                                                  'Armed Services '
                                                                                  'Committee',
                                                                   'entities': {'description': {'urls': []}},
                                                                   'favourites_count': 80,
                                                                   'follow_request_sent': False,
                                                                   'followers_count': 2838397,
                                                                   'following': False,
                                                                   'friends_count': 379,
                                                                   'geo_enabled': True,
                                                                   'has_extended_profile': False,
                                                                   'id': 19394188,
                                                                   'id_str': '19394188',
                                                                   'is_translation_enabled': False,
                                                                   'is_translator': False,
                                                                   'lang': 'en',
                                                                   'listed_count': 20037,
                                                                   'location': 'Phoenix, AZ / '
                                                                               'Washington, DC',
                                                                   'name': 'John McCain',
                                                                   'notifications': False,
                                                                   'profile_background_color': '0E1058',
                                                                   'profile_background_image_url': 'http://pbs.twimg.com/profile_background_images/4035204/Twitter-page-3.jpg',
                                                                   'profile_background_image_url_https': 'https://pbs.twimg.com/profile_background_images/4035204/Twitter-page-3.jpg',
                                                                   'profile_background_tile': False,
                                                                   'profile_banner_url': 'https://pbs.twimg.com/profile_banners/19394188/1421190330',
                                                                   'profile_image_url': 'http://pbs.twimg.com/profile_images/898243253362929664/y1gCTcz1_normal.jpg',
                                                                   'profile_image_url_https': 'https://pbs.twimg.com/profile_images/898243253362929664/y1gCTcz1_normal.jpg',
                                                                   'profile_link_color': '0A0A0A',
                                                                   'profile_sidebar_border_color': 'CB1C15',
                                                                   'profile_sidebar_fill_color': '96A0A6',
                                                                   'profile_text_color': '131515',
                                                                   'profile_use_background_image': False,
                                                                   'protected': False,
                                                                   'screen_name': 'SenJohnMcCain',
                                                                   'statuses_count': 13847,
                                                                   'time_zone': 'Eastern Time (US & '
                                                                                'Canada)',
                                                                   'translator_type': 'none',
                                                                   'url': None,
                                                                   'utc_offset': -18000,
                                                                   'verified': True}},
                                     'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web '
                                               'Client</a>',
                                     'truncated': False,
                                     'user': {'contributors_enabled': False,
                                              'created_at': 'Mon Oct 30 16:08:43 +0000 2017',
                                              'default_profile': True,
                                              'default_profile_image': True,
                                              'description': '',
                                              'entities': {'description': {'urls': []}},
                                              'favourites_count': 0,
                                              'follow_request_sent': False,
                                              'followers_count': 0,
                                              'following': False,
                                              'friends_count': 0,
                                              'geo_enabled': False,
                                              'has_extended_profile': False,
                                              'id': 925031723233972224,
                                              'id_str': '925031723233972224',
                                              'is_translation_enabled': False,
                                              'is_translator': False,
                                              'lang': 'en',
                                              'listed_count': 0,
                                              'location': '',
                                              'name': 'Moa Bridge Test',
                                              'notifications': False,
                                              'profile_background_color': 'F5F8FA',
                                              'profile_background_image_url': None,
                                              'profile_background_image_url_https': None,
                                              'profile_background_tile': False,
                                              'profile_image_url': 'http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
                                              'profile_image_url_https': 'https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
                                              'profile_link_color': '1DA1F2',
                                              'profile_sidebar_border_color': 'C0DEED',
                                              'profile_sidebar_fill_color': 'DDEEF6',
                                              'profile_text_color': '333333',
                                              'profile_use_background_image': True,
                                              'protected': True,
                                              'screen_name': 'moabridge',
                                              'statuses_count': 31,
                                              'time_zone': None,
                                              'translator_type': 'none',
                                              'url': None,
                                              'utc_offset': None,
                                              'verified': False}},
                           'contributors': None,
                           'coordinates': None,
                           'created_at': 'Thu Nov 09 21:58:51 +0000 2017',
                           'current_user_retweet': None,
                           'favorite_count': 0,
                           'favorited': False,
                           'full_text': 'RT @SenJohnMcCain: The allegations against Roy Moore are deeply '
                                        'disturbing and disqualifying. He should immediately step aside '
                                        'and allow th…',
                           'geo': None,
                           'hashtags': [],
                           'id': 928743713047588864,
                           'id_str': '928743713047588864',
                           'in_reply_to_screen_name': None,
                           'in_reply_to_status_id': None,
                           'in_reply_to_user_id': None,
                           'lang': 'en',
                           'location': None,
                           'media': None,
                           'param_defaults': {'contributors': None,
                                              'coordinates': None,
                                              'created_at': None,
                                              'current_user_retweet': None,
                                              'favorite_count': None,
                                              'favorited': None,
                                              'full_text': None,
                                              'geo': None,
                                              'hashtags': None,
                                              'id': None,
                                              'id_str': None,
                                              'in_reply_to_screen_name': None,
                                              'in_reply_to_status_id': None,
                                              'in_reply_to_user_id': None,
                                              'lang': None,
                                              'location': None,
                                              'media': None,
                                              'place': None,
                                              'possibly_sensitive': None,
                                              'quoted_status': None,
                                              'quoted_status_id': None,
                                              'quoted_status_id_str': None,
                                              'retweet_count': None,
                                              'retweeted': None,
                                              'retweeted_status': None,
                                              'scopes': None,
                                              'source': None,
                                              'text': None,
                                              'truncated': None,
                                              'urls': None,
                                              'user': None,
                                              'user_mentions': None,
                                              'withheld_copyright': None,
                                              'withheld_in_countries': None,
                                              'withheld_scope': None},
                           'place': None,
                           'possibly_sensitive': None,
                           'quoted_status': None,
                           'quoted_status_id': None,
                           'quoted_status_id_str': None,
                           'retweet_count': 12986,
                           'retweeted': True,
                           'retweeted_status': Status(ID=928709913953624066, ScreenName='SenJohnMcCain',
                                                      Created='Thu Nov 09 19:44: 32 + 0000 2017',
                                                      Text='The allegations against Roy Moore are deeply disturbing and disqualifying. He should immediately step aside and allow the people of Alabama to elect a candidate they can be proud of.'),
                           'scopes': None,
                           'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
                           'text': None,
                           'truncated': False,
                           'tweet_mode': 'extended',
                           'urls': [],
                           'user': User(ID=925031723233972224, ScreenName='moabridge'),
                           'user_mentions': [User(ID=19394188, ScreenName='SenJohnMcCain')],
                           'withheld_copyright': None,
                           'withheld_in_countries': None,
                           'withheld_scope': None}
