"""empty message

Revision ID: 160e9f85197c
Revises: ed752bbbc436
Create Date: 2018-09-30 14:46:43.320954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '160e9f85197c'
down_revision = 'ed752bbbc436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('instagram_include_link', sa.Boolean(), server_default='SELECT 1', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'instagram_include_link')
    # ### end Alembic commands ###
