"""empty message

Revision ID: 1fe582999fec
Revises: 0b62fbdc595d
Create Date: 2019-11-19 11:12:38.940614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fe582999fec'
down_revision = '0b62fbdc595d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'conditional_posting_old')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('conditional_posting_old', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###
