"""empty message

Revision ID: 21cb95b34051
Revises: 52dbd31d7555
Create Date: 2019-06-04 14:24:24.511600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21cb95b34051'
down_revision = '52dbd31d7555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mastodon_host', sa.Column('defer_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mastodon_host', 'defer_count')
    # ### end Alembic commands ###
