"""add insta stat column

Revision ID: 31955f542d8b
Revises: f5367154ece0
Create Date: 2018-01-31 20:25:42.136472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31955f542d8b'
down_revision = 'f5367154ece0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workerstat', sa.Column('instas', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workerstat', 'instas')
    # ### end Alembic commands ###
