"""empty message

Revision ID: 3ac471544742
Revises: e3efbbd8fe22
Create Date: 2020-05-03 16:03:16.344247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ac471544742'
down_revision = 'e3efbbd8fe22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remove_cw', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('remove_cw')

    # ### end Alembic commands ###
