"""empty message

Revision ID: 52a6ff8551e1
Revises: 8da6f85516eb
Create Date: 2019-01-06 10:03:28.469725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52a6ff8551e1'
down_revision = '8da6f85516eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bridge', 'settings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bridge', sa.Column('settings', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###
