"""empty message

Revision ID: 52dbd31d7555
Revises: 52a6ff8551e1
Create Date: 2019-03-30 14:39:44.743071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52dbd31d7555'
down_revision = '52a6ff8551e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bridge', sa.Column('worker_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bridge', 'worker_id')
    # ### end Alembic commands ###
