"""empty message

Revision ID: 66979188f8c9
Revises: 21cb95b34051
Create Date: 2019-09-08 16:28:16.029836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66979188f8c9'
down_revision = '21cb95b34051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bridgestat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('bridge_id', sa.Integer(), nullable=True),
    sa.Column('tweets', sa.Integer(), nullable=True),
    sa.Column('toots', sa.Integer(), nullable=True),
    sa.Column('instas', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bridge_id'], ['bridge.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bridgestat')
    # ### end Alembic commands ###
