"""empty message

Revision ID: 8da6f85516eb
Revises: dce7a95190f6
Create Date: 2019-01-04 15:10:43.514305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8da6f85516eb'
down_revision = 'dce7a95190f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bridge', 'mastodon_access_code',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('bridge', 'mastodon_host_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bridge', 'mastodon_user',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('bridge', 'twitter_handle',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.alter_column('bridge', 'twitter_oauth_secret',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('bridge', 'twitter_oauth_token',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bridge', 'twitter_oauth_token',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('bridge', 'twitter_oauth_secret',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('bridge', 'twitter_handle',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('bridge', 'mastodon_user',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('bridge', 'mastodon_host_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bridge', 'mastodon_access_code',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    # ### end Alembic commands ###
