"""empty message

Revision ID: dcc7957f3337
Revises: 66979188f8c9
Create Date: 2019-11-18 09:05:38.366272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.

revision = 'dcc7957f3337'
down_revision = '66979188f8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('settings') as bop:
    #     bop.alter_column('conditional_posting', new_column_name='conditional_posting_old')
    # ### end Alembic commands ###
    op.alter_column("settings", column_name='conditional_posting', new_column_name='conditional_posting_old',
        existing_type=sa.Boolean, existing_nullable=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings') as bop:
        bop.alter_column('conditional_posting_old', new_column_name='conditional_posting')

    # ### end Alembic commands ###
