"""empty message

Revision ID: dce7a95190f6
Revises: f74701333e7b
Create Date: 2018-09-30 15:54:15.610080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dce7a95190f6'
down_revision = 'f74701333e7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('conditional_posting', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'conditional_posting')
    # ### end Alembic commands ###
