"""empty message

Revision ID: ed752bbbc436
Revises: a258234b6280
Create Date: 2018-08-23 20:42:34.423305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed752bbbc436'
down_revision = 'a258234b6280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_to_twitter', sa.Boolean(), nullable=False),
    sa.Column('post_private_to_twitter', sa.Boolean(), nullable=False),
    sa.Column('post_unlisted_to_twitter', sa.Boolean(), nullable=False),
    sa.Column('split_twitter_messages', sa.Boolean(), nullable=False),
    sa.Column('post_boosts_to_twitter', sa.Boolean(), nullable=False),
    sa.Column('post_sensitive_behind_link', sa.Boolean(), nullable=False),
    sa.Column('sensitive_link_text', sa.String(length=100), nullable=False),
    sa.Column('post_to_mastodon', sa.Boolean(), nullable=False),
    sa.Column('post_rts_to_mastodon', sa.Boolean(), nullable=False),
    sa.Column('post_quotes_to_mastodon', sa.Boolean(), nullable=False),
    sa.Column('toot_visibility', sa.String(length=40), nullable=False),
    sa.Column('tweets_behind_cw', sa.Boolean(), nullable=False),
    sa.Column('tweet_cw_text', sa.String(length=100), nullable=False),
    sa.Column('instagram_post_to_twitter', sa.Boolean(), nullable=False),
    sa.Column('instagram_post_to_mastodon', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci'
    )
    op.add_column('bridge', sa.Column('t_settings_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bridge', 'settings', ['t_settings_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bridge', type_='foreignkey')
    op.drop_column('bridge', 't_settings_id')
    op.drop_table('settings')
    # ### end Alembic commands ###
