"""add instagram columns

Revision ID: f5367154ece0
Revises: 
Create Date: 2018-01-30 21:53:25.731705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5367154ece0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bridge', sa.Column('instagram_access_code', sa.String(length=80), nullable=True))
    op.add_column('bridge', sa.Column('instagram_account_id', sa.BigInteger(), nullable=True))
    op.add_column('bridge', sa.Column('instagram_handle', sa.String(length=30), nullable=True))
    op.add_column('bridge', sa.Column('instagram_last_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bridge', 'instagram_last_id')
    op.drop_column('bridge', 'instagram_handle')
    op.drop_column('bridge', 'instagram_account_id')
    op.drop_column('bridge', 'instagram_access_code')
    # ### end Alembic commands ###
