"""empty message

Revision ID: f74701333e7b
Revises: 6552c9abedf2
Create Date: 2018-09-30 15:23:20.931117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f74701333e7b'
down_revision = '6552c9abedf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('settings', 'instagram_include_link',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('settings', 'instagram_include_link',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
